---
name: Install APT Dependencies
description: |
  Install debian dependencies required for StackStorm-Exchange pack tests.
author: StackStorm

inputs:
  cache-version:
    required: false
    default: "v0"

runs:
  using: "composite"
  steps:

    - name: Create a directory for debian packages so we can cache it
      # this is what we did on CircleCI. Not sure if it'll work on GHA
      shell: bash
      run: >
        sudo rm -rf /var/cache/apt/archives
        && sudo ln -s ~/apt_cache /var/cache/apt/archives
        && mkdir -p ~/apt_cache/partial

    # hashFiles only reads files relative to GITHUB_WORKSPACE
    - name: Copy apt-packages.txt for caching
      shell: bash
      run: |
        cp ${{ github.action_path }}/apt-packages.txt ${GITHUB_WORKSPACE}/
      # TODO: append pack-defined .github/apt-packages.txt to ${GITHUB_WORKSPACE}/apt-packages.txt

    - name: Cache APT Dependencies
      id: cache-apt-deps
      uses: actions/cache@v2
      with:
        path: |
          ~/apt_cache/*.deb
        key: ${{ inputs.cache-version }}-apt-${{ hashFiles('apt-packages.txt') }}
        restore-keys: |
          ${{ inputs.cache-version }}-apt-

    - name: Install APT Dependencies
      shell: bash
      env:
        CACHE_HIT: ${{steps.cache-apt-deps.outputs.cache-hit}}
        APT_PACKAGES_FILE_PATH: apt-packages.txt
        DEBIAN_FRONTEND: noninteractive
      run: |
        if [[ "${CACHE_HIT}" != 'true' ]]; then
        sudo apt-get -o=Dpkg::Use-Pty=0 -yq update
        fi
        APT_PACKAGES=$(grep -v '^#' "${APT_PACKAGES_FILE_PATH}" | xargs echo -n)
        sudo apt-get -o=Dpkg::Use-Pty=0 -yq install ${APT_PACKAGES}

    - name: Print versions
      shell: bash
      run: |
        set -ex
        jq --version
        gh --version
