---
name: Deploy pack
description: |
  Deploy pack to StackStorm-Exchange index.
  Before using this, make sure to run
  StackStorm-Exchange/ci/.github/actions/checkout,
  StackStorm-Exchange/ci/.github/actions/apt-dependencies,
  StackStorm-Exchange/ci/.github/actions/py-dependencies, and
  StackStorm-Exchange/ci/.github/actions/test.
author: StackStorm

inputs: {}
outputs:
  pack-name:
    description: The pack name pulled from pack.yaml
    value: ${{ steps.pack-name.outputs.pack-name }}

runs:
  using: "composite"
  steps:

    # The .github/actions/test action retrieves the PACK_NAME, so it is already present in the env at this point.

    # checkout pack and index repos

    # create version tags

    # webhook that triggers a workflow in index repo to regen
    #  - rebuild pack index directory
    #    - convert resource metadata to json
    #    - convert config schema to json
    #    - add resource stats to updated pack.yaml
    #  - rebuild index JSON
    #  - copy and optimize icon

    - name: Update exchange.stackstorm.org
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      # TODO: This Makefile has CircleCI assumptions
      run: |
        source ${VIRTUALENV_DIR}/bin/activate
        # ???
