---
name: Run pack metadata tests
description: |
  Run StackStorm-Exchange pack metadata tests.
  Ensure CHANGES.md changed.
  Ensure pack.yaml changed.
  Ensure proposed Pack version > current version.
author: StackStorm

runs:
  using: "composite"
  steps:
    - name: Checkout index repo
      uses: actions/checkout@v3

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35

    - name: Ensure CHANGES.md or CHANGELOG.md and pack.yaml updated
      shell: bash
      run: |
        echo "::group::Ensure CHANGES.md or CHANGELOG.md and pack.yaml updated"
        changed_files=(${{ steps.changed-files.outputs.all_changed_files }})

        if [[ " ${changed_files[*]} " =~ " CHANGES.md " ]]; then
          echo "::notice::CHANGES.md was updated"
        elif [[ " ${changed_files[*]} " =~ " CHANGELOG.md " ]]; then
          echo "::notice::CHANGELOG.md was updated"
        else
          echo "::error::Please update either CHANGES.md or CHANGELOG.md"
          exit 1
        fi

        if [[ " ${changed_files[*]} " =~ " pack.yaml " ]]; then
          echo "::notice::pack.yaml was updated"
        else
          echo "::error::Please update pack.yaml"
          exit 1
        fi
        echo "::endgroup::"

    - name: Ensure semver increased
      shell: bash
      run: |
        echo "::group::Install yq and semver"
        pip3 install --user yq semver
        echo "::endgroup::"

        echo "::group::Get version from pack.yaml (remote and local)"
        CURRENT_VERSION="$(git show origin/${GITHUB_BASE_REF}:pack.yaml | yq -r .version)"
        echo "CURRENT_VERSION=${CURRENT_VERSION}" | tee -a ${GITHUB_ENV}
        PROPOSE_VERSION="$(yq -r .version < pack.yaml)"
        echo "PROPOSE_VERSION=${PROPOSE_VERSION}" | tee -a ${GITHUB_ENV}
        echo "::endgroup::"

        echo "::group::Ensure semver increased"
        # Ensure PACK_VERSION > CURRENT_VERSION
        semver_compare="$(python3 -c 'import semver, sys; print(semver.compare(sys.argv[1], sys.argv[2]))' $PROPOSE_VERSION $CURRENT_VERSION)"
        if [[ $semver_compare -eq -1 ]]; then
          echo "::error::Please increase pack version: proposed pack version ${PROPOSE_VERSION} < current pack version ${CURRENT_VERSION})"
          exit 1
        elif [[ $semver_compare -eq 0 ]]; then
          echo "::error::Please increase pack version: proposed pack version ${PROPOSE_VERSION} = current pack version ${CURRENT_VERSION})"
          exit 1
        elif [[ $semver_compare -eq 1 ]]; then
          echo "::notice::Proposed pack version ${PROPOSE_VERSION} > current pack version ${CURRENT_VERSION})"
        else
          echo "::error::Unexpected version comparison result ${semver_compare}!"
          exit 1
        fi
        echo "::endgroup::"
