---
name: Tag Pack Repo
description: |
  Tag Pack Repo with semver style tag using the version in pack.yaml.
  You must clone the pack to the default location (fetch-depth: 0)
  and install python before running this.
author: StackStorm

outputs:
  pack_version:
    description: The current pack version according to pack.yaml
    value: ${{ env.PACK_VERSION }}
  previous_tag:
    description: The latest tag before running this workflow
    value: ${{ env.LATEST_TAG }}
  created_tag:
    description: true if a new tag was pushed to the pack repo
    value: ${{ steps.git-tag.conclusion == 'skipped' }}

runs:
  using: "composite"
  steps:

    - name: Add checkout path to env context
      shell: bash
      run: |
        echo "CI_DIR=$(realpath ${{ github.action_path }}/../../..)" >> ${GITHUB_ENV}

    # semver.py only uses stdlib deps, so no virtualenv required.

    - name: Get version from pack.yaml
      shell: bash
      run: |
        PACK_VERSION=$(python ${CI_DIR}/.circle/semver.py pack.yaml)
        echo "PACK_VERSION=${PACK_VERSION}" | tee -a >> ${GITHUB_ENV}

    - name: Get latest git tag
      shell: bash
      run: |
        if LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`); then
          echo "LATEST_TAG=${LATEST_TAG}" | tee -a >> ${GITHUB_ENV}
        else
          echo 'LATEST_TAG=""' >> ${GITHUB_ENV}
          echo There are no tags yet.
        fi

    - name: Tag HEAD commit if pack.yaml version has changed
      id: git-tag
      if:  ${{ env.LATEST_TAG != format('v{0}', env.PACK_VERSION) && env.PACK_VERSION != '' }}
      shell: bash
      run: |
        echo "::group::create v${PACK_VERSION} tag on HEAD"
        git tag "v${PACK_VERSION}" HEAD
        echo "::endgroup::"
        echo "::group::Display details about tags"
        set -x
        git tag
        git log --pretty='%h %d' --max-count=1
        set +x
        echo "::endgroup::"
        echo "::group::push v${PACK_VERSION} tag"
        git push origin "v${PACK_VERSION}"
        echo "::endgroup::"
