---
name: Install Python Dependencies
description: |
  Install python dependencies required for StackStorm-Exchange pack tests.
  Before using this, make sure to run
  StackStorm-Exchange/ci/gha/checkout and
  StackStorm-Exchange/ci/gha/apt-dependencies.
author: StackStorm


s:
  python-version:
    required: true
    description: Which python version we should install
  cache-version:
    required: false
    default: "v0"

outputs:
  pip-version:
    description: The installed pip version (pulled from st2.git)
    value: ${{ steps.virtualenv.outputs.pip-version }}

runs:
  using: "composite"
  steps:

    - name: 'Set up Python (${{ inputs.python-version }})'
      shell: bash
      uses: actions/setup-python@v2
      with:
        python-version: '${{ inputs.python-version }}'

    - name: Cache Python Dependencies
      shell: bash
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/virtualenv
        key: ${{ runner.os }}-python-${{ inputs.python-version }}-${{ inputs.cache-version }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-${{ inputs.python-version }}-${{ inputs.cache-version }}-

    - name: Install virtualenv
      shell: bash
      # this should run in the st2 checkout
      working-directory: st2
      run: |
        ./scripts/github/install-virtualenv.sh

    - name: Create ~/virtualenv
      shell: bash
      id: virtualenv
      # this should run in the st2 checkout
      working-directory: st2
      env:
        VIRTUALENV_DIR: "~/virtualenv"
      run: |
        ./scripts/github/install-virtualenv.sh
        PIP_VERSION=$(grep '^PIP_VERSION' Makefile | awk '{print $3}')
        echo "::set-output name=pip-version::${PIP_VERSION}"
        ${VIRTUALENV_DIR}/bin/pip install -U "pip==${PIP_VERSION}" setuptools

    - name: Install StackStorm requirements
      # this should run in the st2 checkout
      shell: bash
      working-directory: st2
      env:
        VIRTUALENV_DIR: "~/virtualenv"
      run: |
        ${VIRTUALENV_DIR}/bin/pip install -r requirements.txt

    - name: Install runners
      shell: bash
      env:
        VIRTUALENV_DIR: "~/virtualenv"
        ACTION_PATH: ${{ github.action_path }}
        ST2_REPO_PATH: st2
      # TODO: This Makefile has CircleCI assumptions
      run: |
        cp ${ACTION_PATH}/../../.circle/Makefile .
        make requirements-ci .install-runners

    - name: Install pack requirements
      shell: bash
      working-directory: pack
      env:
        VIRTUALENV_DIR: "~/virtualenv"
        PACK_REQUIREMENTS_FILE: requirements.txt
        PACK_TESTS_REQUIREMENTS_FILE: requirements-tests.txt
      run: |
        if [[ -f "${PACK_REQUIREMENTS_FILE}" ]]; then
        echo "Installing pack requirements from ${PACK_REQUIREMENTS_FILE}"
        ${VIRTUALENV_DIR}/bin/pip install -r "${PACK_REQUIREMENTS_FILE}"
        fi
        if [[ -f "${PACK_TESTS_REQUIREMENTS_FILE}" ]]; then
        echo "Installing pack tests requirements from ${PACK_TESTS_REQUIREMENTS_FILE}"
        ${VIRTUALENV_DIR}/bin/pip install -r "${PACK_TESTS_REQUIREMENTS_FILE}"
        fi

    - name: Print versions
      shell: bash
      env:
        VIRTUALENV_DIR: "~/virtualenv"
      run: |
        set -ex
        source ${VIRTUALENV_DIR}/activate
        python3 --version
        pip --version
        virtualenv --version
