#!/bin/bash

set -e

my_dir="$(dirname "$0")"

git config --global user.name "StackStorm Exchange"
git config --global user.email "info@stackstorm.com"

# removing broken symlink
sudo rm -f /usr/local/lib/python2.7/dist-packages/setuptools-3.4.4-py2.7.egg

sudo pip install -U pip setuptools virtualenv
sudo apt-get -y install python-dev jq imagemagick

virtualenv ~/virtualenv
. ~/virtualenv/bin/activate

~/virtualenv/bin/pip install -r "$my_dir/requirements.txt"
