#!/bin/sh

set -e

# TODO: figure out how to make deploy.py rebuild the index.
# python ~/packs/.circle/deploy.py pack.yaml "${CIRCLE_PROJECT_REPONAME}"

git clone https://${MACHINE_USER}:${MACHINE_PASSWORD}@github.com/StackStorm-Exchange/index ~/index 2>/dev/null

# Move the pack.yaml file to the index
cp pack.yaml ~/index/v1/packs/"${PACK_NAME}".yaml
# Rebuild the index JSON
~/virtualenv/bin/python ~/ci/.circle/index.py ~/index/v1/
# Commit
git -C ~/index add .
git -C ~/index status

if ! git -C ~/index diff --quiet --exit-code --cached
then

  echo "Updating the index."
  git -C ~/index commit -m "Update the ${PACK_NAME} pack and rebuild the index."
  git -C ~/index push origin 2>/dev/null

  echo "Updating the pack description."
  PACK_DESCRIPTION=$(cat ~/index/v1/index.json | jq ".${PACK_NAME}.description")
  curl -sS --fail -u "${MACHINE_USER}:${MACHINE_PASSWORD}" -X PATCH --header "Content-Type: application/json" \
    -d '{"name": "stackstorm-'"${PACK_NAME}"'", "description": '"${PACK_DESCRIPTION}"'}' \
    "https://api.github.com/repos/StackStorm-Exchange/stackstorm-${PACK_NAME}"

else
  echo "No changes to pack metadata, skipping the index update."
fi
