#!/bin/bash

set -e

# TODO: figure out how to make deploy.py rebuild the index.
# python ~/packs/.circle/deploy.py pack.yaml "${CIRCLE_PROJECT_REPONAME}"
git clone https://${MACHINE_USER}:${MACHINE_PASSWORD}@github.com/StackStorm-Exchange/index ~/index 2>/dev/null

echo "Processing pack ${PACK_NAME}"

# Count content and store it in the index version of pack.yaml
~/virtualenv/bin/python ~/ci/utils/pack_content.py
# Move the pack.yaml file to the index
mkdir -p ~/index/v1/packs/
cp pack.yaml ~/index/v1/packs/"${PACK_NAME}".yaml
git checkout pack.yaml

# Rebuild the index JSON
if [[ $(git -C ~/index status -s) ]]
then
  ~/virtualenv/bin/python ~/ci/.circle/index.py --glob "~/index/v1/packs/*.yaml" --output "~/index/v1/"
else
  echo "No changes in metadata, skipping the index rebuild."
fi

# Check if an icon has been added or changed
ICON_TARGET="${HOME}/index/v1/icons/${PACK_NAME}.png"
if [ -f icon.png ] && { [ ! -f ${ICON_TARGET} ] || ! cmp -s icon.png ${ICON_TARGET}; }
then
  echo "Uploading the pack icon..."
  mkdir -p ~/index/v1/icons/
  cp icon.png ${ICON_TARGET}
  gmic ${ICON_TARGET} -resize 64,64 -output ${ICON_TARGET}
  optipng -o5 ${ICON_TARGET}
  echo "Icon uploaded."
fi

# Commit the index changes
git -C ~/index add .
git -C ~/index status

if ! git -C ~/index diff --quiet --exit-code --cached
then

  echo "Updating the index repo..."
  git -C ~/index commit -m "Update the ${PACK_NAME} pack."
  git -C ~/index push origin 2>/dev/null
  echo "Index updated."

  # echo "Updating the repo description..."
  # PACK_DESCRIPTION=$(cat ~/index/v1/index.json | jq ".packs.${PACK_NAME}.description")
  # curl -sS --fail -u "${MACHINE_USER}:${MACHINE_PASSWORD}" -X PATCH --header "Content-Type: application/json" \
  #  -d '{"name": "stackstorm-'"${PACK_NAME}"'", "description": '"${PACK_DESCRIPTION}"'}' \
  #  "https://api.github.com/repos/StackStorm-Exchange/stackstorm-${PACK_NAME}" > /dev/null 2>&1
  # echo "Description updated."

else
  echo "No changes to pack metadata, skipping the index update."
fi

# Create version tags
PUSH_TAGS=""
METADATA_CHANGES=$(git rev-list --all --no-abbrev -- pack.yaml)
for COMMIT in $(echo $METADATA_CHANGES)
do
  git checkout ${COMMIT} pack.yaml > /dev/null
  VERSION=$(~/virtualenv/bin/python ~/ci/.circle/semver.py pack.yaml 2>/dev/null || true)
  if [[ ${VERSION} ]] && [[ -z $(git rev-parse -q --verify "refs/tags/v${VERSION}") ]]
  then
    echo "Creating tag ${VERSION} for commit ${COMMIT}"
    git tag v${VERSION} ${COMMIT}
    PUSH_TAGS="1"
  fi
  VERSION=""
  TAG=""
done
if [[ ${PUSH_TAGS} ]]
then
  git push --tags origin 2>/dev/null
fi
