#!/usr/bin/env bash

# Script which checks exit code of "test" script under Python 3.6 environment
# and exists with an appropriate code
if [ $# -lt 1 ] ; then
    echo "Usage: $0 <test script exit code>"
    echo "Example: $0 1"
    exit 2
fi

TEST_EXIT_CODE=$1

echo "Original script exit code: ${TEST_EXIT_CODE}"

echo "Exiting with original script exit code (forcing Python 3 build failures)"

exit ${TEST_EXIT_CODE}
