#!/bin/bash

set -e

# make `gh` available for index regeneration
GH_VERSION="${GH_VERSION:-1.5.0}"
[[ -f ~/.apt-cache/gh_${GH_VERSION}_linux_amd64.deb ]] || \
  curl -L -sS --fail -o ~/.apt-cache/gh_${GH_VERSION}_linux_amd64.deb \
  "https://github.com/cli/cli/releases/download/v${GH_VERSION}/gh_${GH_VERSION}_linux_amd64.deb"
sudo dpkg -i ~/.apt-cache/gh_${GH_VERSION}_linux_amd64.deb
