#!/bin/sh

set -e

export PACK_NAME=$(python ~/ci/.circle/validate.py "${CIRCLE_PROJECT_REPONAME}" pack.yaml ~/ci/.circle/pack.yaml.schema)

echo "Validated $PACK_NAME"
echo "export PACK_NAME=$PACK_NAME" >> ~/.circlerc
