#!/bin/bash

set -e

. ~/virtualenv/bin/activate

export CI_DIR=/home/ubuntu/ci
export PYTHONPATH=/tmp/st2/st2common:${PYTHONPATH}
export PACK_NAME=$(~/virtualenv/bin/python ~/ci/.circle/validate.py "${CIRCLE_PROJECT_REPONAME}" pack.yaml)

if [[ -z "${PACK_NAME}" ]]
then
  echo "Unable to retrieve pack name."
  exit 1
fi

GIT_BRANCH=$(git for-each-ref --format='%(objectname) %(refname:short)' refs/heads | awk "/^$(git rev-parse HEAD)/ {print \$2}")

# When running on master branch we want to run checks on all the files / packs
# not only on changes ones.
echo "Running on branch: ${GIT_BRANCH}"
if [ "${GIT_BRANCH}" = "master" ]; then
    echo "Running on master branch, forcing check of all files"
    export FORCE_CHECK_ALL_FILES="true"
fi

# We want to use special config file for tests which sets pack base path to /tmp/packs/
export ST2_CONFIG_FILE=${CI_DIR}/conf/st2.tests.conf

# Note: Travis performs a shallow clone of a single branch which means we end up
# in a detached head state where git-changes-* scripts won't work since master
# branch is not available.
# We fix this by pulling down master branch.
git config remote.origin.fetch refs/heads/*:refs/remotes/origin/*
git fetch origin master

echo "ROOT_DIR=${ROOT_DIR}"

if [ ! -z "${ROOT_DIR}" ]; then
    export ROOT_DIR="${ROOT_DIR}"
    cd ${ROOT_DIR}
fi

cp ~/ci/.circle/Makefile .
make all

EXIT_CODE=$?

echo "Validated $PACK_NAME"
echo "export PACK_NAME=$PACK_NAME" >> ~/.circlerc

exit ${EXIT_CODE}
