name: CI - Build and Test

on:
  workflow_call:
    inputs:
      apt-cache-version:
        required: false
        type: string
        default: "v0"
      py-cache-version:
        required: false
        type: string
        default: "v0"
      enable-common-libs:
        description: |
          When true, use an st2.conf that sets packs.enable_common_libs=true
          see: https://docs.stackstorm.com/reference/sharing_code_sensors_actions.html
        required: false
        type: boolean
        default: false

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    # When parent workflow is named "Build and Test" this shows up as:
    #   "Build and Test / Python 3.6"
    name: 'Python ${{ matrix.python-version-short }}'
    strategy:
      matrix:
        include:
          - python-version-short: 3.6
            python-version: 3.6.13
    steps:
      # eventually replace @gha with @master
      - name: Checkout Pack Repo and CI Repos
        uses: StackStorm-Exchange/ci/.github/actions/checkout@gha
        
      - name: Install APT Dependencies
        uses: StackStorm-Exchange/ci/.github/actions/apt-dependencies@gha
        with:
          cache-version: ${{ inputs.apt-cache-version }}

      - name: Install Python Dependencies
        uses: StackStorm-Exchange/ci/.github/actions/py-dependencies@gha
        with:
          cache-version: ${{ inputs.py-cache-version }}
          python-version: ${{ matrix.python-version }}

      - name: Run pack tests
        uses: StackStorm-Exchange/ci/.github/actions/test@gha
        with:
          enable-common-libs: ${{ inputs.enable-common-libs }}

    services:
      mongo:
        image: mongo:3.4
        ports:
          - 27017:27017
      rabbitmq:
        image: rabbitmq:3
        ports:
          - 5672:5672
      #redis:
      #  image: redis
      #  ports:
      #    - 6379:6379
