name: Tag Release

on:
  workflow_call:
#    inputs:

jobs:
  tag_release:
    runs-on: ubuntu-latest
    name: 'Tag Release'
    steps:
      - name: Checkout Pack Repo
        uses: actions/checkout@v2
        with:
          repository: lm-ydubler/logicmonitor-stackstorm-pack
          fetch-depth: 0
        
      - name: Tag Scripting
        shell: bash
        run: |
          pwd
          ls
          git status
          echo Getting version from pack.yaml...
          version=$(grep 'version:' pack.yaml)
          version="${version#version:}"
          version="$(echo -e "${version}" | tr -d '[:space:]')"
          if [[ -z "$version" ]]; then
            echo pack.yaml version is EMPTY/NULL
            echo ABORTING!
          else
            echo ... version from pack.yaml=$version
            echo
            echo Getting latest git tag ...
            if latestTag=$(git describe --tags `git rev-list --tags --max-count=1`); then
              echo ... latestTag = $latestTag
            else
              echo ... latestTag NOT found
            fi
            echo
            echo Comparing latestTag ($latestTag) to version from pack.yaml ($version) ...
            if [[ "$latestTag" == "v$version" ]]; then
              echo latestTag is the same as version!
            else
              echo "... latestTag is NOT the same as version!"
              echo "... creating new tag with version on most recent commit (HEAD)"
              git tag "v${version}" HEAD
              echo "Listing Tags:"
              git tag
            fi
          fi
