name: Tag Release

on:
  workflow_call:
#    inputs:

jobs:
  tag_release:
    runs-on: ubuntu-latest
    name: 'Tag Release'
    steps:
      - name: Checkout Pack Repo
        uses: actions/checkout@v2
        with:
          repository: lm-ydubler/logicmonitor-stackstorm-pack
          fetch-depth: 0
        
      - name: Tag Scripting
        shell: bash
        run: |
          pwd
          ls
          git status
          tagIsValid="true"
          versionIsValid="true"
          #####################
          # Get latest git tag
          #####################
          if latestTag=$(git describe --tags `git rev-list --tags --max-count=1`); then
            echo latestTag = $latestTag
          else
            echo "latestTag NOT found!"
            tagIsValid="false"
          fi
          if [[ -z "$latestTag" ]]; then
            echo "latestTag is EMPTY/NULL!"
            tagIsValid="false"
          fi
          #############################
          # Get version from pack.yaml
          #############################
          version=$(grep 'version:' pack.yaml)
          version="${version#version:}"
          version="$(echo -e "${version}" | tr -d '[:space:]')"
          if [[ -z "$version" ]]; then
            echo "pack.yaml version is EMPTY/NULL!"
            versionIsValid="false"
          else
            echo "pack.yaml version=$version"
          fi
          if [[ "$tagIsValid" == "true" && "$versionIsValid" == "true" ]]; then
            #############################################
            # Comparing latest tag to pack.yaml's version
            #############################################
            echo comparing $latestTag to $version ...
            if [[ "$latestTag" == "v$version" ]]; then
              ### Tag = Version - Do nothing ###
              echo "latestTag is the same as version!"
            else
              ### Tag != Version - Create new tag with version on most recent commit ###
              echo "latestTag is NOT the same as version!"
              echo "... creating new tag with version on most recent commit ..."
              git tag "$version" HEAD
              git tag
            fi
          else
            echo "Tag or version is invalid!
          fi
          
