name: Tag Release

on:
  workflow_call:
#    inputs:

jobs:
  tag_release:
    runs-on: ubuntu-latest
    name: 'Tag Release'
    steps:
      - name: Checkout Pack Repo
        uses: actions/checkout@v2
        with:
          repository: lm-ydubler/logicmonitor-stackstorm-pack
          fetch-depth: 1
        
      - name: Tag Scripting
        shell: bash
        run: |
          pwd
          ls
          cd ..
          pwd
          ls
          cd ..
          pwd
          ls 
          echo "sup"
