name: Tag Release

on:
  workflow_call:
#    inputs:

jobs:
  tag_release:
    runs-on: ubuntu-latest
    name: 'Tag Release'
    steps:
      - name: Checkout Pack Repo
        uses: actions/checkout@v2
        with:
          repository: lm-ydubler/logicmonitor-stackstorm-pack
          fetch-depth: 1
        
      - name: Tag Scripting
        shell: bash
        run: |
          pwd
          ls
          echo "sup"
          if latestTag=$(git describe --tags `git rev-list --tags --max-count=1`); then
            echo latestTag = $latestTag
            # git checkout $latestTag -b latestTagBranch
          fi
          if [[ -z "$latestTag" ]]; then
            echo "latestTag is NULL"
          fi
