name: Tag Release

on:
  workflow_call:
#    inputs:

jobs:
  tag_release:
    runs-on: ubuntu-latest
    name: 'Tag Release'
    steps:
      - name: Checkout Pack Repo
        uses: actions/checkout@v2
        with:
          repository: lm-ydubler/logicmonitor-stackstorm-pack
          fetch-depth: 0
        
      - name: Tag Scripting
        shell: bash
        run: |
          pwd
          ls
          echo "sup"
          git status
          if latestTag=$(git describe --tags `git rev-list --tags --max-count=1`); then
            echo latestTag = $latestTag
          fi
          if [[ -z "$latestTag" ]]; then
            echo "latestTag is NULL"
          else
            echo "latestTag is NOT NULL"
          fi
          version=$(grep 'version:' pack.yaml)
          echo version in pack.yaml=$version
          version="${version#version:}"
          echo version stripped in pack.yaml=$version
