name: CI - Build and Test

on:
  workflow_call:
    inputs:
      apt-cache-version:
        required: false
        type: string
        default: "v0"
      py-cache-version:
        required: false
        type: string
        default: "v0"
      python-version:
        required: false
        type: string
        default: '["3.8", "3.9", "3.10"]'
      enable-common-libs:
        description: |
          When true, use an st2.conf that sets packs.enable_common_libs=true
          see: https://docs.stackstorm.com/reference/sharing_code_sensors_actions.html
        required: false
        type: boolean
        default: false
      st2-branch:
        required: false
        type: string
        default: master
      lint-configs-branch:
        required: false
        type: string
        default: master
      force-check-all-files:
        required: false
        type: boolean
        default: true

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    # When parent workflow is named "Build and Test" this shows up as:
    #   "Build and Test / Python 3.8,3.9,3.10"
    name: 'Python ${{ matrix.python-version }}'
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python-version) }}
    steps:
      - name: Checkout Pack Repo and CI Repos
        uses: StackStorm-Exchange/ci/.github/actions/checkout@master
        with:
          st2-branch: ${{ inputs.st2-branch }}
          lint-configs-branch: ${{ inputs.lint-configs-branch }}

      - name: Install APT Dependencies
        uses: StackStorm-Exchange/ci/.github/actions/apt-dependencies@master
        with:
          cache-version: ${{ inputs.apt-cache-version }}

      - name: Install Python Dependencies
        uses: StackStorm-Exchange/ci/.github/actions/py-dependencies@master
        with:
          cache-version: ${{ inputs.py-cache-version }}
          python-version: ${{ matrix.python-version }}

      - name: Run pack tests
        uses: StackStorm-Exchange/ci/.github/actions/test@master
        with:
          enable-common-libs: ${{ inputs.enable-common-libs }}
          force-check-all-files: ${{ inputs.force-check-all-files }}

      - name: Ensure CHANGES.md and pack.yaml changed (and Pack version increased)
        if: ${{ github.event_name == 'pull_request' }}
        uses: StackStorm-Exchange/ci/.github/actions/pack-meta@master

    services:
      mongo:
        image: mongo:7.0
        ports:
          - 27017:27017
      rabbitmq:
        image: rabbitmq:4.0
        ports:
          - 5672:5672
      #redis:
      #  image: redis
      #  ports:
      #    - 6379:6379
